AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: consume message from SQS Queue
Resources:
  sqs-add:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: consume message data from SQS Queue
      MemorySize: 128
      Timeout: 300
      Role: 'arn:aws:iam::<accountnumber>:role/<mylambdarole>'
      Environment:
        Variables:
          SQS_QUEUE_URL: https://sqs.<region>.amazonaws.com/<accountnumber>/<queueurl>
